### ISSUE TITLE
Windows: Archives with large paths fail to expand properly

### ISSUE THREAD

**Issue by rnhurt** [aws/aws-codedeploy-agent#46]
I have a pre-packaged Windows application that has very long file paths (ie. vendor/Website/blahblah/shell/client/Applications/ContentTesting/Components/DataSource/MyVeryBigFilenameThatForSomeReasonIsHuge/MyVeryBigFilenameThatForSomeReasonIsHuge.cshtml).  When combined with the default CodeDeploy Agent working directory (ie. C:\ProgramData/Amazon/CodeDeploy/af1d3bc9-b218-4209-bcea-2e2be521f1d7/d-4LZ8QQKED/deployment-archive) I end up with a file path that is greater than 260 characters.  In order to work with file paths that large you have to do some things differently[0].

Can you give me any guidance as to who I might get around this issue?

[0]https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath

**Comment by suryanarayanan** [comment]
Hi,
You can try changing the **_:root_dir_* value in the config file to use a shorter path instead of default and restart the agent. Please remember this means the past deployment history on this instance would be lost and you might run into 'File already exists' error if you've already deployed successfully on the instance. You might have to clean up the old files before starting afresh.
Please see Agent Configuration section for config options http://docs.aws.amazon.com/codedeploy/latest/userguide/host-cleanup.html
Thanks,
Surya.

**Comment by tjkellie** [comment]
I'm also hitting this issue in windows deployments. The 261 char limit is being hit in DownloadBundle and makes the deployment fail every time with applications that have nested folders or files with long names. 

The problem to me is the way the agent names its bundles, I've set the :root_dir to /acd and I still frequently hit it. The path to the deployment archive temp alone is already 100+ chars. Then add in an app folder, a project folder, a sub-folder, and any semi-long filename and it blows up. 

C:\acd\04e4171a-2896-47a5-b7ef-f52c2c75924f\d-5ITO4A39E\deployment-archive-temp\[my Git Org]-[The Repo]-e26b23b991589db4b2e0d1683078efb18086a36d

I can't see restructuring every application repo to fit this issue.
Is there any way to specify a shorter name for the way the agent builds the default deployment path?

**Comment by squadtechnologyinc** [comment]
me too

**Comment by balajiprasadb** [comment]
I'm also facing the same problem. It would be good if CodeDeploy team takes up this issue.

**Comment by rnhurt** [comment]
Interestingly, it looks like [Microsoft is taking care of the problem for us](http://news.softpedia.com/news/microsoft-removes-260-characters-path-length-limit-in-windows-10-redstone-504596.shtml), though it won't affect Windows Server until the next release.  :/

**Comment by pmacpherson** [comment]
me too!  I was looking forward to using code deploy until i ran into this issue.  Having two long guid's in the file path already takes a huge amount of the file path limit.  Would really really like a resolution to this!

**Comment by jody-greene** [comment]
FYI - this is not an issue with Windows. We were able to determine that the issue is with ruby-zip, which codedeploy uses. AWS CodeDeploy team has created an internal ticket, and is working the issue.

**Comment by wickstargazer** [comment]
is this issue fixed? i am having the same issues trying to deploy my system

**Comment by trannzfsg** [comment]
Does anyone has any available updates or workaround on this issue? This is driving me crazy now. Greatly appreciate if anyone knows how to fix it!!

**Comment by computerex** [comment]
Any updates on this?

**Comment by Artemy-Matvienko** [comment]
Still doesn't appear to be fixed.

**Comment by annamataws** [comment]
We are working on getting a fix out

**Comment by iskandar** [comment]
For future searchers, here's a PowerShell way to make Windows Server 2016 (and probably other up-to-date Windows versions) use Long Paths:

```PowerShell
# @see https://github.com/aws/aws-codedeploy-agent/issues/46
# @see https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#paths
Write-Verbose "----> Enabling Long Path Support"
$RegistryPath = "HKLM:SYSTEM\CurrentControlSet\Control\FileSystem"
$Name = "LongPathsEnabled"
New-ItemProperty -Path $RegistryPath -Name $Name -Value 1 -PropertyType DWORD -Force | Out-Null
# You'll want to reboot to make sure; this is Windows we're working with.
Restart-Computer
```

**Comment by tectac** [comment]
Still waiting for a fix!

**Comment by ajgrowney** [comment]
Was the fix released @annamataws ? Wondering if our current CodeDeploy issue is based on this or if it is something else and no ErrorCode on it.

**Comment by annamataws** [comment]
Hi @ajgrowney, the fix has not yet been released. We have been working on our release process so we can start releasing faster and safer, but it has paused releasing these fixes since we are building the new process.

**Comment by brblck** [comment]
Please upgrade to v1.1.2 (our latest stable version):
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-codedeploy-agent-improved-compatibility-amazon-linux-windows-ubuntu/

**Comment by chroto** [comment]
I want to report I'm still seeing the issue on Windows Server 2019 on EC2 on the `Install` event 

`No such file or directory @ rb_sysopen - C:\ProgramData/Amazon/CodeDeploy/e9342b57-1568-40f9-b90a-25bd12b982a0/d-2FDUFPSC5/deployment-archive/veryverylongfilename/etcetcetc`

FWIW I also went through the steps to enable longpaths in the registry for this server

**Comment by aabrowne** [comment]
Same error using latest version on Windows Server 2012 R2: CodeDeploy Host Agent Service v1.3.1.1880

**Comment by adavis217** [comment]
We also still see this error on windows 2019.

**Comment by ifflanb** [comment]
I am also seeing this issue on Windows Server 2022 Datacenter when using CodeDeploy at the Install event stage.
I added the registry setting for long file paths which fixed the previous issue that it was having unpacking the archive but now I get the same error at the install stage.

**Comment by philstrong** [comment]
AFAIK, this must be enabled during the build of the agent as well. It's in our backlog to address
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

**Comment by mwjones-aws** [comment]
This was addressed with the 1.4.0 agent release. Docs coming soon.

**Comment by rnhurt** [comment]
Well, it only  took 6 years but I'm glad it's getting fixed.  :grin:

**Comment by t0shiii** [comment]
Docs for supporting large paths in Windows can be found [here](https://docs.aws.amazon.com/codedeploy/latest/userguide/troubleshooting-deployments.html#troubleshooting-long-file-paths)
